### ISSUE TITLE
Criar uma branch dev no repositório

### ISSUE THREAD

**Issue by ProfAndrea** [TheWinterComes/TrabalhoWEB#1]
Vão proteger a branch main para push

**Comment by TheWinterComes** [comment]
1° Criar a branch dev;
2° Acessar as configurações, na área geral alterar a branch default para a dev;
3° Após isso acessar a área de branches, e adicionar proteção na branch main, e marcar a opção de exigir uma solicitação pull antes de mesclar e salvar a proteção.
