### ISSUE TITLE
Criar um projeto HTML om o uso do Bootstrap como css

### ISSUE THREAD

**Issue by ProfAndrea** [TheWinterComes/TrabalhoWEB#2]
Criar uma página html, vincular o bootstrap e adicionar um elemento qualquer

**Comment by cookiemorim** [comment]
1. Acessar o site do BOOTSTRAP, e copiar os comandos para linkar o bootstrap ao html;
2. Fazer a base de html e colocar os comandos já copiados do site do bootstrap;
3. Escolher um tipo de bootstrap para fazer, o escolhido foi o Carousel;
4. Após fazer o código vincular as imagens;
5. E acessar o arquivo html no navegador e ver se está funcionando.
